export const usOpenData = {
  "id": "d59637dc-7f7a-4cd8-a4af-0c5d419a9f39",
  "name": "U.S. Open",
  "event_type": "stroke",
  "purse": 12000000.0,
  "winning_share": 2160000.0,
  "currency": "USD",
  "points": 600,
  "start_date": "2019-06-13",
  "end_date": "2019-06-16",
  "course_timezone": "US/Pacific",
  "venue": {
    "id": "da323e92-6ff1-4f03-8974-4d5b3bf1e357",
    "name": "Pebble Beach Golf Links",
    "city": "Pebble Beach",
    "state": "CA",
    "zipcode": "93953",
    "country": "USA",
    "courses": [{
      "id": "283cfbf1-86f7-4de4-8749-d02a40383e35",
      "name": "Spyglass Hill Golf Course",
      "yardage": 6858,
      "par": 72,
      "holes": [{
        "number": 1,
        "par": 5,
        "yardage": 595
      }, {
        "number": 2,
        "par": 4,
        "yardage": 349
      }, {
        "number": 3,
        "par": 3,
        "yardage": 152
      }, {
        "number": 4,
        "par": 4,
        "yardage": 370
      }, {
        "number": 5,
        "par": 3,
        "yardage": 183
      }, {
        "number": 6,
        "par": 4,
        "yardage": 416
      }, {
        "number": 7,
        "par": 5,
        "yardage": 529
      }, {
        "number": 8,
        "par": 4,
        "yardage": 399
      }, {
        "number": 9,
        "par": 4,
        "yardage": 431
      }, {
        "number": 10,
        "par": 4,
        "yardage": 407
      }, {
        "number": 11,
        "par": 5,
        "yardage": 528
      }, {
        "number": 12,
        "par": 3,
        "yardage": 178
      }, {
        "number": 13,
        "par": 4,
        "yardage": 441
      }, {
        "number": 14,
        "par": 5,
        "yardage": 560
      }, {
        "number": 15,
        "par": 3,
        "yardage": 125
      }, {
        "number": 16,
        "par": 4,
        "yardage": 462
      }, {
        "number": 17,
        "par": 4,
        "yardage": 325
      }, {
        "number": 18,
        "par": 4,
        "yardage": 408
      }]
    }, {
      "id": "32700de7-18b8-41a2-80fd-28d5ee44a48b",
      "name": "Monterey Peninsula Shore Course",
      "yardage": 6838,
      "par": 70,
      "holes": [{
        "number": 1,
        "par": 4,
        "yardage": 454
      }, {
        "number": 2,
        "par": 4,
        "yardage": 391
      }, {
        "number": 3,
        "par": 3,
        "yardage": 155
      }, {
        "number": 4,
        "par": 4,
        "yardage": 401
      }, {
        "number": 5,
        "par": 4,
        "yardage": 349
      }, {
        "number": 6,
        "par": 5,
        "yardage": 548
      }, {
        "number": 7,
        "par": 3,
        "yardage": 226
      }, {
        "number": 8,
        "par": 4,
        "yardage": 454
      }, {
        "number": 9,
        "par": 3,
        "yardage": 224
      }, {
        "number": 10,
        "par": 5,
        "yardage": 544
      }, {
        "number": 11,
        "par": 3,
        "yardage": 176
      }, {
        "number": 12,
        "par": 5,
        "yardage": 599
      }, {
        "number": 13,
        "par": 4,
        "yardage": 401
      }, {
        "number": 14,
        "par": 3,
        "yardage": 190
      }, {
        "number": 15,
        "par": 4,
        "yardage": 415
      }, {
        "number": 16,
        "par": 4,
        "yardage": 500
      }, {
        "number": 17,
        "par": 4,
        "yardage": 430
      }, {
        "number": 18,
        "par": 4,
        "yardage": 381
      }]
    }, {
      "id": "62adb452-8f11-4c5f-b672-7ac014ee4028",
      "name": "Pebble Beach Golf Links",
      "yardage": 6816,
      "par": 72,
      "holes": [{
        "number": 1,
        "par": 4,
        "yardage": 381
      }, {
        "number": 2,
        "par": 5,
        "yardage": 502
      }, {
        "number": 3,
        "par": 4,
        "yardage": 390
      }, {
        "number": 4,
        "par": 4,
        "yardage": 331
      }, {
        "number": 5,
        "par": 3,
        "yardage": 188
      }, {
        "number": 6,
        "par": 5,
        "yardage": 513
      }, {
        "number": 7,
        "par": 3,
        "yardage": 106
      }, {
        "number": 8,
        "par": 4,
        "yardage": 418
      }, {
        "number": 9,
        "par": 4,
        "yardage": 466
      }, {
        "number": 10,
        "par": 4,
        "yardage": 446
      }, {
        "number": 11,
        "par": 4,
        "yardage": 380
      }, {
        "number": 12,
        "par": 3,
        "yardage": 202
      }, {
        "number": 13,
        "par": 4,
        "yardage": 399
      }, {
        "number": 14,
        "par": 5,
        "yardage": 573
      }, {
        "number": 15,
        "par": 4,
        "yardage": 397
      }, {
        "number": 16,
        "par": 4,
        "yardage": 403
      }, {
        "number": 17,
        "par": 3,
        "yardage": 178
      }, {
        "number": 18,
        "par": 5,
        "yardage": 543
      }]
    }, {
      "id": "cf04b6a0-f5da-494f-b7e7-46d9d1a6ab97",
      "name": "Poppy Hills",
      "yardage": 7002,
      "par": 71,
      "holes": [{
        "number": 1,
        "par": 5,
        "yardage": 527
      }, {
        "number": 2,
        "par": 3,
        "yardage": 161
      }, {
        "number": 3,
        "par": 4,
        "yardage": 421
      }, {
        "number": 4,
        "par": 4,
        "yardage": 399
      }, {
        "number": 5,
        "par": 4,
        "yardage": 385
      }, {
        "number": 6,
        "par": 3,
        "yardage": 223
      }, {
        "number": 7,
        "par": 4,
        "yardage": 444
      }, {
        "number": 8,
        "par": 3,
        "yardage": 179
      }, {
        "number": 9,
        "par": 5,
        "yardage": 515
      }, {
        "number": 10,
        "par": 4,
        "yardage": 443
      }, {
        "number": 11,
        "par": 3,
        "yardage": 202
      }, {
        "number": 12,
        "par": 4,
        "yardage": 447
      }, {
        "number": 13,
        "par": 5,
        "yardage": 629
      }, {
        "number": 14,
        "par": 4,
        "yardage": 478
      }, {
        "number": 15,
        "par": 3,
        "yardage": 185
      }, {
        "number": 16,
        "par": 4,
        "yardage": 414
      }, {
        "number": 17,
        "par": 4,
        "yardage": 415
      }, {
        "number": 18,
        "par": 5,
        "yardage": 535
      }]
    }]
  }
}