export const majors = [{
  "id": "fdf12aec-74d2-4f2e-9e0b-00481a32fd34",
  "name": "Masters Tournament",
  "event_type": "stroke",
  "purse": 11000000.0,
  "winning_share": 1980000.0,
  "currency": "USD",
  "points": 600,
  "start_date": "2019-04-11",
  "end_date": "2019-04-14",
  "course_timezone": "US/Eastern",
  "seasons": [{
    "id": "42cb037c-a813-49b3-a64e-1355e7bf4038",
    "year": 2019,
    "tour": {
      "id": "b52068af-28e4-4e91-bdbb-037591b0ff84",
      "alias": "pga",
      "name": "PGA Tour"
    }
  }, {
    "id": "6a06d55e-0f07-4b5b-8abf-c228fa554c4c",
    "year": 2019,
    "tour": {
      "id": "e97bb87a-6347-40d0-8c8c-3d0f54a41043",
      "alias": "EURO",
      "name": "European Tour"
    }
  }],
  "venue": {
    "id": "d555598a-aed0-44fe-b659-4250264c7820",
    "name": "Augusta National Golf Club",
    "city": "Augusta",
    "state": "GA",
    "zipcode": "30904",
    "country": "USA",
    "courses": [{
      "id": "7e9462a5-66ea-4205-b37a-81884e3653cf",
      "name": "Augusta National",
      "yardage": 7435,
      "par": 72,
      "holes": [{
        "number": 1,
        "par": 4,
        "yardage": 445,
        "description": "Tea Olive"
      }, {
        "number": 2,
        "par": 5,
        "yardage": 575,
        "description": "Pink Dogwood"
      }, {
        "number": 3,
        "par": 4,
        "yardage": 350,
        "description": "Flowering Pitch"
      }, {
        "number": 4,
        "par": 3,
        "yardage": 240,
        "description": "Flowering Crabapple"
      }, {
        "number": 5,
        "par": 4,
        "yardage": 455,
        "description": "Magnolia"
      }, {
        "number": 6,
        "par": 3,
        "yardage": 180,
        "description": "Juniper"
      }, {
        "number": 7,
        "par": 4,
        "yardage": 450,
        "description": "Pampas"
      }, {
        "number": 8,
        "par": 5,
        "yardage": 570,
        "description": "Yellow Jasmine"
      }, {
        "number": 9,
        "par": 4,
        "yardage": 460,
        "description": "Carolina Cherry"
      }, {
        "number": 10,
        "par": 4,
        "yardage": 495,
        "description": "Camellia"
      }, {
        "number": 11,
        "par": 4,
        "yardage": 505,
        "description": "White Dogwood"
      }, {
        "number": 12,
        "par": 3,
        "yardage": 155,
        "description": "Golden Bell"
      }, {
        "number": 13,
        "par": 5,
        "yardage": 510,
        "description": "Azalea"
      }, {
        "number": 14,
        "par": 4,
        "yardage": 440,
        "description": "Chinese Fir"
      }, {
        "number": 15,
        "par": 5,
        "yardage": 530,
        "description": "Firethorn"
      }, {
        "number": 16,
        "par": 3,
        "yardage": 170,
        "description": "Redbud"
      }, {
        "number": 17,
        "par": 4,
        "yardage": 440,
        "description": "Nandina"
      }, {
        "number": 18,
        "par": 4,
        "yardage": 465,
        "description": "Holly"
      }]
    }]
  }
},
  {
    "id": "b850e0a9-c15d-4263-8122-03df781e2b8d",
    "name": "PGA Championship",
    "event_type": "stroke",
    "purse": 11000000.0,
    "winning_share": 1980000.0,
    "currency": "USD",
    "points": 600,
    "start_date": "2019-05-16",
    "end_date": "2019-05-19",
    "course_timezone": "US/Eastern",
    "venue": {
      "id": "eec96d45-6285-4de0-bd78-fb21fedea3e4",
      "name": "Bethpage State Park, Black Course",
      "city": "Farmingdale",
      "state": "NY",
      "zipcode": "11735",
      "country": "USA",
      "courses": [{
        "id": "f8f7546a-1482-4da9-877f-68bcb0c705e5",
        "name": "Bethpage State Park, Black Course",
        "yardage": 7468,
        "par": 71,
        "holes": [{
          "number": 1,
          "par": 4,
          "yardage": 430
        }, {
          "number": 2,
          "par": 4,
          "yardage": 389
        }, {
          "number": 3,
          "par": 3,
          "yardage": 230
        }, {
          "number": 4,
          "par": 5,
          "yardage": 517
        }, {
          "number": 5,
          "par": 4,
          "yardage": 478
        }, {
          "number": 6,
          "par": 4,
          "yardage": 408
        }, {
          "number": 7,
          "par": 5,
          "yardage": 553
        }, {
          "number": 8,
          "par": 3,
          "yardage": 210
        }, {
          "number": 9,
          "par": 4,
          "yardage": 460
        }, {
          "number": 10,
          "par": 4,
          "yardage": 502
        }, {
          "number": 11,
          "par": 4,
          "yardage": 435
        }, {
          "number": 12,
          "par": 4,
          "yardage": 501
        }, {
          "number": 13,
          "par": 5,
          "yardage": 608
        }, {
          "number": 14,
          "par": 3,
          "yardage": 161
        }, {
          "number": 15,
          "par": 4,
          "yardage": 478
        }, {
          "number": 16,
          "par": 4,
          "yardage": 490
        }, {
          "number": 17,
          "par": 3,
          "yardage": 207
        }, {
          "number": 18,
          "par": 4,
          "yardage": 411
        }]
      }]
    }
  },
  {
    "id": "d59637dc-7f7a-4cd8-a4af-0c5d419a9f39",
    "name": "U.S. Open",
    "event_type": "stroke",
    "purse": 12000000.0,
    "winning_share": 2160000.0,
    "currency": "USD",
    "points": 600,
    "start_date": "2019-06-13",
    "end_date": "2019-06-16",
    "course_timezone": "US/Pacific",
    "venue": {
      "id": "da323e92-6ff1-4f03-8974-4d5b3bf1e357",
      "name": "Pebble Beach Golf Links",
      "city": "Pebble Beach",
      "state": "CA",
      "zipcode": "93953",
      "country": "USA",
      "courses": [{
        "id": "283cfbf1-86f7-4de4-8749-d02a40383e35",
        "name": "Spyglass Hill Golf Course",
        "yardage": 6858,
        "par": 72,
        "holes": [{
          "number": 1,
          "par": 5,
          "yardage": 595
        }, {
          "number": 2,
          "par": 4,
          "yardage": 349
        }, {
          "number": 3,
          "par": 3,
          "yardage": 152
        }, {
          "number": 4,
          "par": 4,
          "yardage": 370
        }, {
          "number": 5,
          "par": 3,
          "yardage": 183
        }, {
          "number": 6,
          "par": 4,
          "yardage": 416
        }, {
          "number": 7,
          "par": 5,
          "yardage": 529
        }, {
          "number": 8,
          "par": 4,
          "yardage": 399
        }, {
          "number": 9,
          "par": 4,
          "yardage": 431
        }, {
          "number": 10,
          "par": 4,
          "yardage": 407
        }, {
          "number": 11,
          "par": 5,
          "yardage": 528
        }, {
          "number": 12,
          "par": 3,
          "yardage": 178
        }, {
          "number": 13,
          "par": 4,
          "yardage": 441
        }, {
          "number": 14,
          "par": 5,
          "yardage": 560
        }, {
          "number": 15,
          "par": 3,
          "yardage": 125
        }, {
          "number": 16,
          "par": 4,
          "yardage": 462
        }, {
          "number": 17,
          "par": 4,
          "yardage": 325
        }, {
          "number": 18,
          "par": 4,
          "yardage": 408
        }]
      }, {
        "id": "32700de7-18b8-41a2-80fd-28d5ee44a48b",
        "name": "Monterey Peninsula Shore Course",
        "yardage": 6838,
        "par": 70,
        "holes": [{
          "number": 1,
          "par": 4,
          "yardage": 454
        }, {
          "number": 2,
          "par": 4,
          "yardage": 391
        }, {
          "number": 3,
          "par": 3,
          "yardage": 155
        }, {
          "number": 4,
          "par": 4,
          "yardage": 401
        }, {
          "number": 5,
          "par": 4,
          "yardage": 349
        }, {
          "number": 6,
          "par": 5,
          "yardage": 548
        }, {
          "number": 7,
          "par": 3,
          "yardage": 226
        }, {
          "number": 8,
          "par": 4,
          "yardage": 454
        }, {
          "number": 9,
          "par": 3,
          "yardage": 224
        }, {
          "number": 10,
          "par": 5,
          "yardage": 544
        }, {
          "number": 11,
          "par": 3,
          "yardage": 176
        }, {
          "number": 12,
          "par": 5,
          "yardage": 599
        }, {
          "number": 13,
          "par": 4,
          "yardage": 401
        }, {
          "number": 14,
          "par": 3,
          "yardage": 190
        }, {
          "number": 15,
          "par": 4,
          "yardage": 415
        }, {
          "number": 16,
          "par": 4,
          "yardage": 500
        }, {
          "number": 17,
          "par": 4,
          "yardage": 430
        }, {
          "number": 18,
          "par": 4,
          "yardage": 381
        }]
      }, {
        "id": "62adb452-8f11-4c5f-b672-7ac014ee4028",
        "name": "Pebble Beach Golf Links",
        "yardage": 6816,
        "par": 72,
        "holes": [{
          "number": 1,
          "par": 4,
          "yardage": 381
        }, {
          "number": 2,
          "par": 5,
          "yardage": 502
        }, {
          "number": 3,
          "par": 4,
          "yardage": 390
        }, {
          "number": 4,
          "par": 4,
          "yardage": 331
        }, {
          "number": 5,
          "par": 3,
          "yardage": 188
        }, {
          "number": 6,
          "par": 5,
          "yardage": 513
        }, {
          "number": 7,
          "par": 3,
          "yardage": 106
        }, {
          "number": 8,
          "par": 4,
          "yardage": 418
        }, {
          "number": 9,
          "par": 4,
          "yardage": 466
        }, {
          "number": 10,
          "par": 4,
          "yardage": 446
        }, {
          "number": 11,
          "par": 4,
          "yardage": 380
        }, {
          "number": 12,
          "par": 3,
          "yardage": 202
        }, {
          "number": 13,
          "par": 4,
          "yardage": 399
        }, {
          "number": 14,
          "par": 5,
          "yardage": 573
        }, {
          "number": 15,
          "par": 4,
          "yardage": 397
        }, {
          "number": 16,
          "par": 4,
          "yardage": 403
        }, {
          "number": 17,
          "par": 3,
          "yardage": 178
        }, {
          "number": 18,
          "par": 5,
          "yardage": 543
        }]
      }, {
        "id": "cf04b6a0-f5da-494f-b7e7-46d9d1a6ab97",
        "name": "Poppy Hills",
        "yardage": 7002,
        "par": 71,
        "holes": [{
          "number": 1,
          "par": 5,
          "yardage": 527
        }, {
          "number": 2,
          "par": 3,
          "yardage": 161
        }, {
          "number": 3,
          "par": 4,
          "yardage": 421
        }, {
          "number": 4,
          "par": 4,
          "yardage": 399
        }, {
          "number": 5,
          "par": 4,
          "yardage": 385
        }, {
          "number": 6,
          "par": 3,
          "yardage": 223
        }, {
          "number": 7,
          "par": 4,
          "yardage": 444
        }, {
          "number": 8,
          "par": 3,
          "yardage": 179
        }, {
          "number": 9,
          "par": 5,
          "yardage": 515
        }, {
          "number": 10,
          "par": 4,
          "yardage": 443
        }, {
          "number": 11,
          "par": 3,
          "yardage": 202
        }, {
          "number": 12,
          "par": 4,
          "yardage": 447
        }, {
          "number": 13,
          "par": 5,
          "yardage": 629
        }, {
          "number": 14,
          "par": 4,
          "yardage": 478
        }, {
          "number": 15,
          "par": 3,
          "yardage": 185
        }, {
          "number": 16,
          "par": 4,
          "yardage": 414
        }, {
          "number": 17,
          "par": 4,
          "yardage": 415
        }, {
          "number": 18,
          "par": 5,
          "yardage": 535
        }]
      }]
    }
  },
  {
    "id": "4524eac8-9713-43c5-a742-290d8ab434ba",
    "name": "The Open Championship",
    "event_type": "stroke",
    "purse": 10500000.0,
    "winning_share": 1890000.0,
    "currency": "USD",
    "points": 600,
    "start_date": "2019-07-18",
    "end_date": "2019-07-21",
    "course_timezone": "Europe/London",
    "venue": {
      "id": "4021bffa-e93d-4b7e-bef2-39172c09cd7a",
      "name": "Royal Portrush Golf Club",
      "city": "Portrush",
      "country": "GBR",
      "courses": [{
        "id": "8b2c3c75-0956-465f-9237-2baee9d1365b",
        "name": "Dunluce Links",
        "yardage": 7337,
        "par": 72,
        "holes": [{
          "number": 1,
          "par": 4,
          "yardage": 420,
          "description": "Hughie's"
        }, {
          "number": 2,
          "par": 5,
          "yardage": 577,
          "description": "Giant's Grave"
        }, {
          "number": 3,
          "par": 3,
          "yardage": 176,
          "description": "Islay"
        }, {
          "number": 4,
          "par": 4,
          "yardage": 499,
          "description": "Fred Daly's"
        }, {
          "number": 5,
          "par": 4,
          "yardage": 403,
          "description": "White Rocks"
        }, {
          "number": 6,
          "par": 3,
          "yardage": 191,
          "description": "Harry Colt's"
        }, {
          "number": 7,
          "par": 5,
          "yardage": 572,
          "description": "Curran Point"
        }, {
          "number": 8,
          "par": 4,
          "yardage": 435,
          "description": "Dunluce"
        }, {
          "number": 9,
          "par": 4,
          "yardage": 430,
          "description": "P.G. Stevenson's"
        }, {
          "number": 10,
          "par": 4,
          "yardage": 448,
          "description": "Himalayas"
        }, {
          "number": 11,
          "par": 5,
          "yardage": 473,
          "description": "Tavern"
        }, {
          "number": 12,
          "par": 5,
          "yardage": 530,
          "description": "Dhu Varren"
        }, {
          "number": 13,
          "par": 3,
          "yardage": 192,
          "description": "Feather Bed"
        }, {
          "number": 14,
          "par": 4,
          "yardage": 464,
          "description": "Causeway"
        }, {
          "number": 15,
          "par": 4,
          "yardage": 427,
          "description": "Skerries"
        }, {
          "number": 16,
          "par": 3,
          "yardage": 230,
          "description": "Calamity Corner"
        }, {
          "number": 17,
          "par": 4,
          "yardage": 405,
          "description": "Purgatory"
        }, {
          "number": 18,
          "par": 4,
          "yardage": 465,
          "description": "Babington's"
        }]
      }]
    }
  }
] 